# Set workflow name
name: Deploy To Staging

# Set events that trigger the workflow
on:
  push:
    branches:
      - staging

# Set jobs to be executed in the workflow
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        run: ./test-pipeline.sh
  build:
    needs: tests
    name: Build And Deploy To Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Deploy to staging
        run: |
          echo 'Add staging deployment script here...'
