name: Deploy Laravel API to AWS EB

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Prepare deployment package
        run: zip -r deploy.zip . -x@.ebignore

#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v21
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          application_name: ${{ secrets.EB_APP_NAME }}
#          environment_name: ${{ secrets.EB_ENV_NAME_WEB }}
#          version_label: app-${{ github.sha }}
#          region: ${{ secrets.AWS_REGION }}
#          deployment_package: deploy.zip
