# Set workflow name
name: Deploy To Production

# Set events that triggers the workflow
on:
  push:
    branches:
      - main

# Set jobs to be executed in the workflow
jobs:
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Run tests
        run: ./test-pipeline.sh
  build:
    needs: tests
    name: Build And Deploy To Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Deploy to production
        run: |
          echo 'Add production deployment script here...'
